name: publish

on:
  push:
    tags:
      - '@.*\/.*@[0-9]+\.[0-9]+\.[0-9]+'
        # https://regex101.com/r/QdT1jO/1

permissions:
  contents: read
  id-token: write # needed for provenance data generation

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0
          submodules: recursive
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      - run: bunx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - run: bun install --no-cache
      - uses: nrwl/nx-set-shas@v4

      - name: publish packages
        run: bun nx release -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }
          NPM_CONFIG_PROVENANCE: true

      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: bun nx fix-ci
        if: always()
